project_id = "sonpin"

[auth.email.template.confirmation]
subject = "Sonpin 驗證電子郵件"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.magic_link]
subject = "Sonpin 登入連結"
content_path = "./supabase/templates/magic_link.html"
